# MGT5493 Programming in Business Analytics
#### Lab 1: NumPy & Pandas Fundamentals for Business Data
#### Duration: 2 hrs

#### Dataset: store_sale.csv

#### Tools: Jupyter notebook

#### GTA: Kris Ruochen Qi

In [ ]:
# Install packages
import numpy as np
import pandas as pd

In [2]:
# Creating a numpy array

weekly_sales = np.array([100, 200, 300, 400, 500])
print(weekly_sales)

[100 200 300 400 500]

In [3]:
weekly_sales

array([100, 200, 300, 400, 500])

In [6]:
# Compute summary of statisitics

mean_value = np.mean(weekly_sales)
print("Mean value:", mean_value)

max_value = np.max(weekly_sales)
print("Max value:", max_value)

min_value = np.min(weekly_sales)
print("Min value:", min_value)

std_value = np.std(weekly_sales)
print("Standard Deviation:", std_value)
print("================================")
print("Summary of statistics:")
print("Mean value:", round(mean_value,2))
print("Max value:", round(max_value,2))
print("Min value:", round(min_value,2))
print("Standard Deviation:", round(std_value,2))

Mean value: 300.0
Max value: 500
Min value: 100
Standard Deviation: 141.4213562373095
================================
Summary of statistics:
Mean value: 300.0
Max value: 500
Min value: 100
Standard Deviation: 141.42

In [7]:
# Or, using the simple math function from python
mean_value_0 = weekly_sales.mean()
max_value_0 = weekly_sales.max()
min_value_0 = weekly_sales.min()
std_value_0 = weekly_sales.std()    

print(mean_value_0, max_value_0, min_value_0, std_value_0)

300.0 500 100 141.4213562373095

In [11]:
# load dataset with pandas


df = pd.read_csv("/Users/2798523q/Documents/PhD/Internship/GTA/MGT5493 Data Programming in Business Analytics/Lab/Lab 1 NumPy amp pandas Fundamentals for Business Data/store_sales.csv")
print(df.head(10))

data_path = "/Users/2798523q/Documents/PhD/Internship/GTA/MGT5493 Data Programming in Business Analytics/Lab/Lab 1 NumPy amp pandas Fundamentals for Business Data/store_sales.csv"

df_1 = pd.read_csv(data_path, parse_dates=['Date'])
print("================================")
print(df_1.head(10))

         Date     Store     Sales   Profit
0  2025-01-01  North_01  11324.56  2548.33
1  2025-01-02  North_01  15310.72   963.62
2  2025-01-03  North_01  10796.86  2026.25
3  2025-01-04  North_01  12781.21  2287.73
4  2025-01-05  North_01  11700.81  2723.53
5  2025-01-06  North_01  14983.12  2756.32
6  2025-01-07  North_01  15686.44  3263.57
7  2025-01-08  North_01  11688.23  2362.48
8  2025-01-09  North_01  11487.79  2673.29
9  2025-01-10  North_01  13317.21  2249.39
================================
        Date     Store     Sales   Profit
0 2025-01-01  North_01  11324.56  2548.33
1 2025-01-02  North_01  15310.72   963.62
2 2025-01-03  North_01  10796.86  2026.25
3 2025-01-04  North_01  12781.21  2287.73
4 2025-01-05  North_01  11700.81  2723.53
5 2025-01-06  North_01  14983.12  2756.32
6 2025-01-07  North_01  15686.44  3263.57
7 2025-01-08  North_01  11688.23  2362.48
8 2025-01-09  North_01  11487.79  2673.29
9 2025-01-10  North_01  13317.21  2249.39

In [16]:
# Inspect dataset

display(df_1.info())
print("================================================================")
display(df.info())

# looking for the different data types by the functions of parse_dates

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    240 non-null    datetime64[us]
 1   Store   240 non-null    str
 2   Sales   240 non-null    float64
 3   Profit  240 non-null    float64
dtypes: datetime64[us](1), float64(2), str(1)
memory usage: 7.6 KB

None

================================================================
<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    240 non-null    str
 1   Store   240 non-null    str
 2   Sales   240 non-null    float64
 3   Profit  240 non-null    float64
dtypes: float64(2), str(2)
memory usage: 7.6 KB

None

In [ ]:
# Descriptive statistics of the dataset
display(df_1.describe())

                      Date         Sales       Profit
count                  240    240.000000   240.000000
mean   2025-01-30 12:00:00  12251.011917  2270.494917
min    2025-01-01 00:00:00   7231.020000   344.060000
25%    2025-01-15 18:00:00  10789.447500  1542.637500
50%    2025-01-30 12:00:00  12018.265000  2159.285000
75%    2025-02-14 06:00:00  13860.307500  2769.107500
max    2025-03-01 00:00:00  18490.830000  6359.730000
std                    NaN   2168.703907   920.826854

In [ ]:
# Compute store_level totals

# functions of Aggregation by "groupby" and "agg"
store_level_totals = df_1.groupby("Store", as_index=False)
store_level_totals = store_level_totals.agg(Total_Sales = ("Sales", "sum"), Total_Profit = ("Profit", "sum"))
print(store_level_totals)

store_level_totals_1 = df_1.groupby("Store")
store_level_totals_1 = store_level_totals_1.agg(Total_Sales = ("Sales", "sum"), Total_Profit = ("Profit", "sum"))

print("================================")
print(store_level_totals_1)

# as_index = False means that the group keys will not be used as the index of the resulting DataFrame. 
# Instead, the group keys will be included as regular columns in the output DataFrame. 
# This is useful when you want to keep the original structure of the DataFrame and avoid having the group keys as the index.

      Store  Total_Sales  Total_Profit
0   East_01    837304.78     164753.68
1  North_01    794381.57     139718.45
2  South_01    646282.16     118326.22
3   West_01    662274.35     122120.43
================================
          Total_Sales  Total_Profit
Store
East_01     837304.78     164753.68
North_01    794381.57     139718.45
South_01    646282.16     118326.22
West_01     662274.35     122120.43

In [28]:
# Sorting the values by certain order and columns
store_level_totals.sort_values(by="Total_Sales", ascending=False) # default is ascending
print(store_level_totals)

      Store  Total_Sales  Total_Profit
0   East_01    837304.78     164753.68
1  North_01    794381.57     139718.45
2  South_01    646282.16     118326.22
3   West_01    662274.35     122120.43

In [29]:
# Combining all codes together
store = (df_1.groupby("Store", as_index=False)
         .agg(Total_Sales = ("Sales", "sum"), 
              Total_Profit = ("Profit", "sum"))
         .sort_values(by="Total_Sales", ascending=False))
store

      Store  Total_Sales  Total_Profit
0   East_01    837304.78     164753.68
1  North_01    794381.57     139718.45
3   West_01    662274.35     122120.43
2  South_01    646282.16     118326.22

In [30]:
# Sort and Display Top 5 Records
top5_store = df_1.sort_values(by="Sales", ascending=False).head(5)
top5_store

          Date    Store     Sales   Profit
135 2025-01-16  East_01  18490.83  5073.91
122 2025-01-03  East_01  17949.91  6359.73
153 2025-02-03  East_01  17729.11  4443.71
173 2025-02-23  East_01  17187.96  3473.71
152 2025-02-02  East_01  16816.65  3614.90